version: '1.0'

services:

  # frontend:
  #   image: pizzafrontend
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   environment: 
  #     - backendUrl=http://backend
  #   ports:
  #     - "5001:80"
  #   depends_on: 
  #     - backend

# A vantage de usar docker-compose é que não a necessidade de usar alguns comando do Dockerfile, ex: $ docker run -it --rm -p 5200:80 --name contosopizzainfodois contosopizzainfoapi

  MicrosservicosModDois:
    image: contosopizzainfoapi
    build: 
      context: MicrosservicosModDois
      dockerfile: Dockerfile
    ports: 
      - "5000:80"
